using System.Collections.Generic;
using System.Threading.Tasks;
using System.Reflection;
using System.Linq;
using System.Text;
using System.IO;
using System;

namespace Documentation
{
    public static class Program
    {
        public static int Main(string[] args)
        {
            try
            {
                Assembly asm = Assembly.LoadFrom(args[0]);
                FileInfo targ = new FileInfo(args[1]);

                if (!targ.Exists)
                    targ.Create();

                StringBuilder sb = new StringBuilder();

                sb.AppendLine($@"<!-- Autogenerated : {DateTime.Now:yyyy-MM-dd HH:mm:ss:ffffff} -->
## See# (See Sharp) documentation

<img src=""./favicon.ico"" height=""50""/>

_**WARNING:** The library's soruce code is not for the faint of heart. It is ported legacy-code from an older project._
");

                using (FileStream fs = new FileStream(targ.FullName, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.Read))
                using (StreamWriter sw = new StreamWriter(fs))
                {
                    fs.Seek(0, SeekOrigin.Begin);
                    sw.Write(sb.ToString());
                }

                return 0;
            }
            catch
            {
                return -1;
            }
        }
    }
}
